[package]
name = "aoc2025"
version = "0.1.0"
authors = ["Olivia Kaufman <olivia@olivia.wtf>"]
edition = "2024"

[dependencies]
reqwest = {version = "0.12.24", features = ["blocking"]}

[dev-dependencies]
httpmock = "0.8.2"
rand = "0.9.2"
tempfile = "3.23.0"
